version: '3'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # - KAFKA_NO_PARTITION_WARNING=1

  # kafdrop:
  #   image: obsidiandynamics/kafdrop:latest
  #   environment:
  #     KAFKA_BROKERCONNECT: kafka:9092
  #   ports:
  #     - "9000:9000"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fenaRootPassword
      MYSQL_USER: fenaUser
      MYSQL_PASSWORD: fenaPassword
      MYSQL_DATABASE: fenaDB
    ports:
      - "3306:3306"
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
  
  backend:
    build: ./backend/
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKER: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_USER: fenaUser
      MYSQL_PASSWORD: fenaPassword
      MYSQL_DATABASE: fenaDB
    depends_on:
      - kafka
      - mysql

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1